<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class DeliveryResource extends JsonResource
{
    /**
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'business_id' => $this->business_id,
            'branch_id' => $this->branch_id,
            'customer_id' => $this->customer_id,
            'customer_address_id' => $this->customer_address_id,
            'assigned_driver_id' => $this->assigned_driver_id,
            'created_by' => $this->created_by,
            'delivery_number' => $this->delivery_number,
            'tracking_code' => $this->tracking_code,
            'public_tracking_token' => $this->public_tracking_token,
            'delivery_pin' => $this->delivery_pin,
            'status' => $this->status,
            'pickup_name' => $this->pickup_name,
            'pickup_phone' => $this->pickup_phone,
            'pickup_address' => $this->pickup_address,
            'pickup_latitude' => $this->pickup_latitude,
            'pickup_longitude' => $this->pickup_longitude,
            'dropoff_name' => $this->dropoff_name,
            'dropoff_phone' => $this->dropoff_phone,
            'dropoff_address' => $this->dropoff_address,
            'dropoff_latitude' => $this->dropoff_latitude,
            'dropoff_longitude' => $this->dropoff_longitude,
            'payment_method' => $this->payment_method,
            'amount_to_collect' => $this->amount_to_collect,
            'delivery_fee' => $this->delivery_fee,
            'special_instruction' => $this->special_instruction,
            'customer_location_confirmed_at' => $this->customer_location_confirmed_at,
            'assigned_at' => $this->assigned_at,
            'accepted_at' => $this->accepted_at,
            'started_at' => $this->started_at,
            'arrived_at' => $this->arrived_at,
            'delivered_at' => $this->delivered_at,
            'failed_at' => $this->failed_at,
            'cancelled_at' => $this->cancelled_at,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
            'business' => $this->whenLoaded('business', fn () => [
                'id' => $this->business->id,
                'name' => $this->business->name,
                'business_code' => $this->business->business_code,
                'phone' => $this->business->phone,
                'email' => $this->business->email,
                'status' => $this->business->status,
            ]),
            'branch' => $this->whenLoaded('branch', fn () => $this->branch ? [
                'id' => $this->branch->id,
                'business_id' => $this->branch->business_id,
                'name' => $this->branch->name,
                'phone' => $this->branch->phone,
                'status' => $this->branch->status,
            ] : null),
            'customer' => $this->whenLoaded('customer', fn () => [
                'id' => $this->customer->id,
                'business_id' => $this->customer->business_id,
                'user_id' => $this->customer->user_id,
                'name' => $this->customer->name,
                'phone' => $this->customer->phone,
                'email' => $this->customer->email,
                'status' => $this->customer->status,
            ]),
            'customer_address' => $this->whenLoaded('customerAddress', fn () => $this->customerAddress ? [
                'id' => $this->customerAddress->id,
                'business_id' => $this->customerAddress->business_id,
                'customer_id' => $this->customerAddress->customer_id,
                'label' => $this->customerAddress->label,
                'region' => $this->customerAddress->region,
                'district' => $this->customerAddress->district,
                'ward' => $this->customerAddress->ward,
                'street' => $this->customerAddress->street,
                'landmark' => $this->customerAddress->landmark,
                'building_instruction' => $this->customerAddress->building_instruction,
                'latitude' => $this->customerAddress->latitude,
                'longitude' => $this->customerAddress->longitude,
                'is_default' => $this->customerAddress->is_default,
                'is_verified' => $this->customerAddress->is_verified,
                'verified_at' => $this->customerAddress->verified_at,
            ] : null),
            'assigned_driver' => $this->whenLoaded('assignedDriver', fn () => $this->assignedDriver ? [
                'id' => $this->assignedDriver->id,
                'business_id' => $this->assignedDriver->business_id,
                'branch_id' => $this->assignedDriver->branch_id,
                'name' => $this->assignedDriver->name,
                'phone' => $this->assignedDriver->phone,
                'status' => $this->assignedDriver->status,
            ] : null),
            'items' => DeliveryItemResource::collection($this->whenLoaded('items')),
            'status_logs' => $this->whenLoaded('statusLogs', fn () => $this->statusLogs->map(fn ($log): array => [
                'id' => $log->id,
                'delivery_id' => $log->delivery_id,
                'changed_by' => $log->changed_by,
                'from_status' => $log->from_status,
                'to_status' => $log->to_status,
                'note' => $log->note,
                'created_at' => $log->created_at,
                'updated_at' => $log->updated_at,
                'changed_by_user' => $log->relationLoaded('changedBy') && $log->changedBy ? [
                    'id' => $log->changedBy->id,
                    'name' => $log->changedBy->name,
                ] : null,
            ])),
            'payment' => $this->whenLoaded('payment', fn () => $this->payment ? [
                'id' => $this->payment->id,
                'delivery_id' => $this->payment->delivery_id,
                'business_id' => $this->payment->business_id,
                'driver_id' => $this->payment->driver_id,
                'payment_method' => $this->payment->payment_method,
                'expected_amount' => $this->payment->expected_amount,
                'collected_amount' => $this->payment->collected_amount,
                'payment_status' => $this->payment->payment_status,
                'reference_number' => $this->payment->reference_number,
                'note' => $this->payment->note,
                'collected_at' => $this->payment->collected_at,
            ] : null),
            'proof' => $this->whenLoaded('proof', fn () => $this->proof ? [
                'id' => $this->proof->id,
                'delivery_id' => $this->proof->delivery_id,
                'driver_id' => $this->proof->driver_id,
                'recipient_name' => $this->proof->recipient_name,
                'recipient_phone' => $this->proof->recipient_phone,
                'pin_verified' => $this->proof->pin_verified,
                'has_photo' => $this->proof->photo_path !== null,
                'has_signature' => $this->proof->signature_path !== null,
                'delivered_latitude' => $this->proof->delivered_latitude,
                'delivered_longitude' => $this->proof->delivered_longitude,
                'note' => $this->proof->note,
                'delivered_at' => $this->proof->delivered_at,
            ] : null),
            'failure' => $this->whenLoaded('failure', fn () => $this->failure ? [
                'id' => $this->failure->id,
                'delivery_id' => $this->failure->delivery_id,
                'driver_id' => $this->failure->driver_id,
                'failed_delivery_reason_id' => $this->failure->failed_delivery_reason_id,
                'reason_note' => $this->failure->reason_note,
                'failed_latitude' => $this->failure->failed_latitude,
                'failed_longitude' => $this->failure->failed_longitude,
                'has_photo' => $this->failure->photo_path !== null,
                'failed_at' => $this->failure->failed_at,
                'reason' => $this->failure->relationLoaded('failedDeliveryReason') && $this->failure->failedDeliveryReason ? [
                    'id' => $this->failure->failedDeliveryReason->id,
                    'name' => $this->failure->failedDeliveryReason->name,
                ] : null,
            ] : null),
        ];
    }
}
